const escapeHtml = (value) => String(value == null ? '' : value)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#039;');

function buildLeadReport({ empresa, nome, cargo, email, telefone, protocol, when }) {
  const row = (label, value) => `<div class="item"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong></div>`;
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lead NR-1 — ${escapeHtml(empresa)}</title><style>:root{--ink:#171717;--muted:#6f6f69;--paper:#f4f2ed;--line:#ddd9d1;--accent:#f8ad00}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,sans-serif}.page{width:min(900px,calc(100% - 32px));margin:32px auto;background:#fff;border:1px solid var(--line)}header{padding:34px 42px;border-top:8px solid var(--accent);border-bottom:1px solid var(--line)}.brand{font-size:20px;font-weight:700;letter-spacing:.09em}.subbrand,.eyebrow{font-size:10px;letter-spacing:.24em;text-transform:uppercase;color:var(--muted)}.subbrand{margin-top:5px}.content{padding:46px 42px 52px}.eyebrow{margin-bottom:14px}h1{font:500 clamp(30px,5vw,52px)/1.08 Georgia,serif;margin:0 0 34px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));border-top:1px solid var(--line);border-left:1px solid var(--line)}.item{padding:20px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.item small{display:block;font-size:9px;letter-spacing:.16em;text-transform:uppercase;color:var(--muted);margin-bottom:8px}.item strong{font-size:15px;font-weight:500}.request{margin-top:34px;padding:28px;background:#f8f7f4;border-left:4px solid var(--accent);line-height:1.7}footer{display:flex;justify-content:space-between;gap:20px;padding:22px 42px;background:var(--ink);color:#fff;font-size:11px}@media(max-width:620px){.page{width:100%;margin:0}.content,header{padding-left:24px;padding-right:24px}.grid{grid-template-columns:1fr}footer{padding:20px 24px;flex-direction:column}}</style></head><body><main class="page"><header><div class="brand">BENÍCIO</div><div class="subbrand">ADVOGADOS ASSOCIADOS</div></header><section class="content"><div class="eyebrow">Lead · Saúde mental e NR-1</div><h1>${escapeHtml(empresa)}</h1><div class="grid">${row('Responsável', nome)}${row('Cargo / área', cargo)}${row('E-mail', email)}${row('Telefone', telefone)}</div><div class="request">Solicitou os materiais Guia de Conformidade à NR-1 e Decisões Difíceis de RH.</div></section><footer><span>Protocolo ${escapeHtml(protocol)}</span><span>Gerado em ${escapeHtml(when)} · Brasília</span></footer></main></body></html>`;
}

module.exports = { buildLeadReport };
